server:
  port: 8001
  error:
    include-message: always

spring:
  config:
    activate:
      on-profile: local
    import: "optional:configserver:http://localhost:8010"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

logging:
  level:
    root: INFO
    com.spring.cloud.product: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

management:
  server:
    port: 8001
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always # actuator에서 디테일한 정보들을 확인하기 위해 설정