server:
  port: 8761

spring:
  config:
    activate:
      on-profile: local
    import: "optional:configserver:http://localhost:8010"

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    responseCacheUpdateIntervalMs: 5000

management.endpoints.web.exposure.include: "*"